# These are supported funding model platforms

patreon: dr_dimitru
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=N3X827SNXVMK8&item_name=Open+Source+Software&currency_code=USD&source=url
